openapi: 3.0.0
info:
  version: 1.0.0
  title: Digits LCD
  description: >-
    This is an OpenAPI Specification created by oas-wizard
    (https://github.com/pafmon/oas-wizard)  
  contact:
    name: Carnuare
    email: carnuare@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /api/v1/segments:
    post:
      description: Returns list of LCD strings
      operationId: getSegments
      requestBody:
        description: t is the size and n the numbers that you wish to transform
        content:
          application/json:
            schema:
              type: array
              example: [
                      {
                          "t": 2,
                          "n": 12345
                      },
                      {
                          "t": 3,
                          "n": 67890
                      },
                      {
                          "t": 0,
                          "n": 0
                      }
                  ]
      responses:
        '200':
          description: Response List
          content:
            application/json:
              schema:
                type: array
                example: [
                              "        --     --            -- \n   |      |      |   |  |   |   \n   |      |      |   |  |   |   \n        --     --     --     -- \n   |   |         |      |      |\n   |   |         |      |      |\n        --     --            -- \n",
                              " ---     ---     ---     ---     --- \n|           |   |   |   |   |   |   |\n|           |   |   |   |   |   |   |\n|           |   |   |   |   |   |   |\n ---             ---     ---         \n|   |       |   |   |       |   |   |\n|   |       |   |   |       |   |   |\n|   |       |   |   |       |   |   |\n ---             ---     ---     --- \n",
                              "  \n  \n  \n"
                          ]
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    response:
      type: object
      properties:
        data:
          type: string
          minLength: 1
      required:
        - data
